import express from 'express';
import { protect } from '../middleware/auth.js';
import Meeting from '../models/Meeting.js';
import Task from '../models/Task.js';
import { GoogleGenerativeAI } from '@google/generative-ai';

const router = express.Router();

let genAI = null;
if (process.env.GEMINI_API_KEY) {
  genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
}

// @desc    Translate text
// @route   POST /api/ai/translate
// @access  Private
router.post('/translate', protect, async (req, res) => {
  const { text, targetLang } = req.body;

  try {
    if (!text || !targetLang) {
      return res.status(400).json({ message: 'Text and target language are required' });
    }

    if (!genAI) {
      return res.status(500).json({ message: 'Gemini API key is not configured.' });
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const prompt = `You are a professional translator. Translate the following text into ${targetLang}. Only return the translated text without any quotes or extra explanation.\n\nText to translate:\n${text}`;
    
    const result = await model.generateContent(prompt);
    
    res.json({ translatedText: result.response.text().trim() });
  } catch (error) {
    console.error('AI Translation error:', error);
    res.status(500).json({ message: 'AI Translation error' });
  }
});

// @desc    Summarize a completed meeting and extract actions
// @route   POST /api/ai/summarize
// @access  Private
router.post('/summarize', protect, async (req, res) => {
  const { meetingCode } = req.body;

  try {
    if (!meetingCode) {
      return res.status(400).json({ message: 'Meeting code is required' });
    }

    let meeting = null;
    if (global.isMockDB) {
      meeting = global.mockDb.meetings.find((m) => m.code === meetingCode);
    } else {
      meeting = await Meeting.findOne({ code: meetingCode });
    }

    if (!meeting) {
      return res.status(404).json({ message: 'Meeting not found' });
    }

    if (!genAI) {
      return res.status(500).json({ message: 'Gemini API key is not configured.' });
    }

    const transcriptText = meeting.transcript.map(line => `${line.userName}: ${line.text}`).join('\n');
    const chatText = meeting.chatMessages.map(msg => `${msg.senderName}: ${msg.text}`).join('\n');
    
    const prompt = `
      Analyze the following meeting transcript and chat logs.
      Title: ${meeting.title}
      Transcript:
      ${transcriptText}
      Chat:
      ${chatText}
      
      Respond in pure JSON format with the following structure:
      {
        "overview": "A brief 2-3 sentence overview of the meeting",
        "topics": ["topic 1", "topic 2"],
        "decisions": ["decision 1", "decision 2"],
        "tone": "A short phrase describing the tone",
        "actionItems": [
          {
            "text": "The task description",
            "assignee": "Name of the person assigned to the task (or 'Unassigned')"
          }
        ]
      }
    `;

    const model = genAI.getGenerativeModel({ 
      model: "gemini-1.5-flash",
      generationConfig: { responseMimeType: "application/json" },
      systemInstruction: "You are an AI meeting assistant. Always output valid JSON."
    });

    const result = await model.generateContent(prompt);
    const parsedResponse = JSON.parse(result.response.text());
    
    // Map extracted actions to proper format with dates
    const extractedActions = (parsedResponse.actionItems || []).map(action => ({
      text: action.text,
      assignee: action.assignee !== 'Unassigned' ? action.assignee : meeting.hostName,
      status: 'todo',
      dueDate: new Date(Date.now() + 3600000 * 24 * 3) // Default to 3 days
    }));

    const aiSummary = {
      overview: parsedResponse.overview,
      topics: parsedResponse.topics,
      decisions: parsedResponse.decisions,
      tone: parsedResponse.tone
    };

    // Update meeting details
    if (global.isMockDB) {
      const idx = global.mockDb.meetings.findIndex((m) => m.code === meetingCode);
      if (idx !== -1) {
        global.mockDb.meetings[idx].status = 'completed';
        global.mockDb.meetings[idx].summary = aiSummary;
        global.mockDb.meetings[idx].actionItems = extractedActions;
        global.mockDb.meetings[idx].endedAt = new Date();
        meeting = global.mockDb.meetings[idx];

        extractedActions.forEach((action) => {
          global.mockDb.tasks.push({
            _id: new Date().getTime().toString() + Math.random().toString(36).substr(2, 5),
            title: action.text,
            description: `Auto-generated by AI Agent from meeting "${meeting.title}"`,
            assignedTo: action.assignee,
            meetingId: meetingCode,
            status: action.status,
            priority: 'medium',
            dueDate: action.dueDate,
            creator: meeting.hostName,
            createdAt: new Date()
          });
        });
      }
    } else {
      meeting.status = 'completed';
      meeting.summary = aiSummary;
      meeting.actionItems = extractedActions;
      meeting.endedAt = new Date();
      await meeting.save();

      for (const action of extractedActions) {
        await Task.create({
          title: action.text,
          description: `Auto-generated by AI Agent from meeting "${meeting.title}"`,
          assignedTo: action.assignee,
          meetingId: meetingCode,
          status: action.status,
          priority: 'medium',
          dueDate: action.dueDate,
          creator: meeting.hostName
        });
      }
    }

    res.json({
      success: true,
      summary: meeting.summary,
      actionItems: meeting.actionItems
    });
  } catch (error) {
    console.error('AI Summarize error:', error);
    res.status(500).json({ message: 'Server error generating summary' });
  }
});

// @desc    General chat with AI agent
// @route   POST /api/ai/chat
// @access  Private
router.post('/chat', protect, async (req, res) => {
  const { message, meetingCode } = req.body;

  try {
    if (!message) {
      return res.status(400).json({ message: 'Message is required' });
    }

    if (!genAI) {
      return res.status(500).json({ message: 'Gemini API key is not configured.' });
    }

    // Prepare context
    let context = `You are the IntellMeet AI Assist agent. The user asking the question is ${req.user.name}.`;
    
    if (meetingCode) {
      let meeting = null;
      if (global.isMockDB) {
        meeting = global.mockDb.meetings.find((m) => m.code === meetingCode);
      } else {
        meeting = await Meeting.findOne({ code: meetingCode });
      }

      if (meeting) {
        const transcriptLines = meeting.transcript.map(line => `[${new Date(line.timestamp).toLocaleTimeString()}] ${line.userName}: ${line.text}`).join('\n');
        context += `\n\nActive Meeting Context:\nTitle: ${meeting.title}\nTranscript so far:\n${transcriptLines}`;
      }
    }

    const model = genAI.getGenerativeModel({ 
      model: "gemini-1.5-flash",
      systemInstruction: context
    });

    const result = await model.generateContent(message);

    res.json({ response: result.response.text() });
  } catch (error) {
    console.error('AI Chat Error:', error);
    res.status(500).json({ message: 'Server error in AI Chat agent' });
  }
});

export default router;
